services:
  mongo:
    image: mongo:7
    container_name: lesson14-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - lesson14_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: lesson14mongo

volumes:
  lesson14_mongo_data: